name: Setup Go
description: 'Sets up Go environment with private modules'
inputs:
  stainless-api-key:
    required: false
    description: the value of the STAINLESS_API_KEY secret
runs:
  using: composite
  steps:
    - uses: stainless-api/retrieve-github-access-token@1f03f929b746c5b03dcdafa2bebbb18ca5672e1a # v1.0.0
      if: github.repository == 'stainless-sdks/anthropic-cli'
      id: get_token
      with:
        repo: stainless-sdks/anthropic-go
        stainless-api-key: ${{ inputs.stainless-api-key }}

    - name: Configure Git for access to the Go SDK's staging repo
      if: github.repository == 'stainless-sdks/anthropic-cli'
      shell: bash
      run: git config --global url."https://x-access-token:${{ steps.get_token.outputs.github_access_token }}@github.com/stainless-sdks/anthropic-go".insteadOf "https://github.com/stainless-sdks/anthropic-go"

    - name: Setup go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: ./go.mod

    - name: Bootstrap
      shell: bash
      run: ./scripts/bootstrap
